version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - backend

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - infrastructure

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
    labels:
      - dependencies
      - infrastructure
